[workspace]
allow_dirty = true
publish_allow_dirty = true
changelog_config = "cliff.toml"
changelog_update = true
dependencies_update = true
git_tag_enable = true
git_release_enable = true
pr_labels = ["release"]
semver_check = false
publish_timeout = "10m" # set a timeout for `cargo publish`
